#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.pnpm/@craigmiller160+js-config@1.0.14_cross-env@7.0.3_fp-ts@2.16.2/node_modules/lint-staged/bin/lint-staged.js --config ./node_modules/@craigmiller160/js-config/configs/lintstaged/.lintstagedrc